services:
  db:
    image: postgres:16
    container_name: subscription_postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: subscription_service
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - .env
    restart: always

  migrate:
    image: migrate/migrate:v4.16.2
    container_name: subscription_migrate
    volumes:
      - ./migrations:/migrations
    command:
      [
        "-path", "/migrations",
        "-database", "postgres://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}?sslmode=disable",
        "up"
      ]
    depends_on:
      - db
    restart: "on-failure"

volumes:
  pg_data:
